### ISSUE TITLE
Condition Reports don't fully implement the PID spec.

### ISSUE THREAD

**Issue by jonlidgard** [jmriego/Fino#1]
There is a problem in the effects calculator. It doesn't correctly implement the PID specification:

If the number of Condition report blocks is equal to the number of axes for the effect, then the first report
block applies to the first axis, the second applies to the second axis, and so on. For example, a two-axis
spring condition with CP Offset set to zero in both Condition report blocks would have the same effect as
the joystick self-centering spring. When a condition is defined for each axis in this way, the effect must
not be rotated.

If there is a single Condition report block for an effect with more than one axis, then the direction along
which the parameters of the Condition report block are in effect is determined by the direction parameters
passed in the Direction field of the Effect report block. For example, a friction condition rotated 45
degrees (in polar coordinates) would resist joystick motion in the northeast-southwest direction but would
have no effect on joystick motion in the northwest-southeast direction.

Your fix assumes there will always be 2 parameter blocks with DIRECTION_ENABLE but according to the spec that's not necessarily the case.
The code needs to count the number of parameter blocks set (as the effect get's built from the HID reports) & if more than one block, apply the relevant parameter block to each axis. If there is only one parameter block, then the effect needs to be scaled by the angle_ratio. (paragraph 2)

I've got a fix but it's based on the YukMingLaw code so doesn't incorporate your changes.
[https://github.com/jonlidgard/ArduinoJoystickWithFFBLibrary/tree/conditionEffect](https://github.com/jonlidgard/ArduinoJoystickWithFFBLibrary/tree/conditionEffect)
The code needs testing as I don't have an Arduino setup but it's based on other stuff I'm doing that does work. Hopefully it's of some use!

**Comment by jmriego** [comment]
hi! Sorry I never got any notification and didn't see this issue until now.
yes, you're totally right, I was aware of this limitation and was planning on adding it at some point but I'll definitely have a look at your code! That's definitely going to be useful for adding it. Thanks!

**Comment by jmriego** [comment]
hi @jonlidgard !

I was having a look at this and there are some things I'm not clear on. I'm finding difficult to find info about it.
Why do you have this code:
```
bool useForceDirectionForConditionEffect = (effect.enableAxis == DIRECTION_ENABLE && effect.conditionsCount == 1);
```

Are springs and dampers not supposed to take into account direction somehow?
Reading page 12 of this doc: https://raw.githubusercontent.com/jmriego/Fino/master/reference/pid1_01.pdf

> If there is a single Condition report block for an effect with more than one axis, then the direction alongwhich the parameters of the Condition report block are in effect is determined by the direction parameterspassed in the Direction field of the Effect report block. For example, a friction condition rotated 45degrees (in polar coordinates) would resist joystick motion in the northeast-southwest direction but wouldhave no effect on joystick motion in the northwest-southeast direction

I think this code is not including that. Also one of the things I had to change was to include the `directionX` and `directionY` parameters. I'm not completely sure if they actually map to X and Y axes, primary and secondary axis or we actually need one direction per axis in the joystick

**Comment by jmriego** [comment]
By the way, I also need to have a look at the rest of the code as I removed some code that was related only to driving wheels. I did that because I really had to bring the sketch size down but that's not necessary any more. I'll include that as well

**Comment by jmriego** [comment]
hi @jonlidgard ! I have uploaded some code to test more than two condition reports and also fix the direction in condition reports that was not working properly.
I don't have access to a joystick for a few days but can you have a look at #8  and let me know your thoughts?

By the way, which program are you using to feed 3 axis FFB effects? I didn't find any that worked properly

**Comment by jonlidgard** [comment]
Sure , I’m a bit busy for a couple of days but will have a look when I get the chance.
regards
Jon

**Comment by jmriego** [comment]
no rush at all. I already merged what I have done so far into the main branch so you can use that. You'd have to create a joystick with x,y,z axes and modify the FFB_AXIS_COUNT to 3

**Comment by jmriego** [comment]
I also just added the damper and friction filters as an array that gets generated depending on the number of FFB axes now. This should be fixed now. Let me know if you find any issues!
