### ISSUE TITLE
Several Probs

### ISSUE THREAD

**Issue by fcppenta** [jmriego/Fino#10]
Hi

Just tried this, I'm having several issues. I'm using X and Y potentiometers, 2 motors. The spring effect for instance I have always to put an offset of about 60 on the ForceTest software. That way I get the center in X, but never the center in Y. The Y effect moves to one the extreme side.
Another strange effect is the Grooves, first time I click on the checkbox, It starts to move fast to one of the Y extremes. Next if I uncheck and recheck the checkbox it starts to be normal effect, but never let change the spacing time.
A bit weird, but good work anyway what you are trying to do.
Also I'm using your master branch.

Paulo Moreira

**Comment by jmriego** [comment]
hi @fcppenta !

The issue with the Grooves effect is fixed but requires you to use a different VID and PID for the Arduino. From what I have found out online it seems like Windows detects the Arduino does not have that capability (Start Delay) and the only way to force it to redetect hardware is changing the VID and PID: http://liveelectronics.musinou.net/MIDIdeviceName.php

You want to set these two lines to whatever ids you like:
```
micromusinou.build.vid=0x045e
micromusinou.build.pid=0x001b
```

**Comment by jmriego** [comment]
The issue with the X and Y seem to be related to either the potentiometers themselves or something you are doing when sending it the position.
To verify the potentiometers, have you checked whether the joystick position work as expected?
If that's not it, check in your code what do you have for these values:
```
    effects[0].springMaxPosition = maxX;
    effects[1].springMaxPosition = maxY;
    effects[0].springPosition = pos[0];
    effects[1].springPosition = pos[1];
```

**Comment by fcppenta** [comment]
Well, concerning the potentiometers, they are working well, under windows and calibrating the joystick they are working very well. I also have the effects as you mentioned. Unfortunately I can't change the VID/PID, I don't know why, always is the Android Leonardo that it goes...

**Comment by jmriego** [comment]
about changing the VID/PID you can do that with the info on this link:  http://liveelectronics.musinou.net/MIDIdeviceName.php
by following the instructions there and then modifying the boards.txt to have a different vid and pid. If you do that, Arduino IDE will show you a new board:
![image](https://user-images.githubusercontent.com/15045950/114312604-78d6b700-9af3-11eb-90d0-403012027a84.png)

about the issue with bad spring effect I think you could add code similar to this to debug what the Joystick library is receiving:
```
Serial.print('springMaxPositionY ');
Serial.print(effects[1].springMaxPosition);
Serial.print('springPositionY ');
Serial.println(effects[1].springPosition);
```

then check if the numbers make sense. If they do, check the forces generated
```
Serial.print('forceY ');
Serial.print(forces[1]);
```

**Comment by fcppenta** [comment]
The spring effect has to be corrected for the hardware that I'm developping, so here is my modifications, also I converted the 0,10000 forces range to -255,255 for this effect in spific, and now yes, I got a very well spring effect on my Yoke

 case USB_EFFECT_SPRING://8
	    	force = ConditionForceCalculator(effect, NormalizeRange(_effect_params.springPosition, m_effect_params[axis].springMaxPosition), condition) * angle_ratio * springGain;

			if (force > 0) {
				force = force - 5000;
			}
			else {
				force = force + 5000;
			}

			force = ((force * 512) / 10000);

			if (force < -255)
			{
				force = -255;
			}
			else if (force > 255)
			{
				force = 255;
			}

**Comment by jmriego** [comment]
I would recommend that instead of trying to change the effects one by one for your hardware that you start testing the constant force effect in ForceTest. Change the strength of that force and that way you get an understanding of what the magnitude effect does. You then can change the magnitudes in `config.h` for your motors. That file has a multiplier value for each gain effect and that's probably all you need to adjust

**Comment by fcppenta** [comment]
Yeah, I saw it right now :)
I have to have a PWM for the motors, so I have to send force values from 0 to 255 to the hardware.

**Comment by jmriego** [comment]
oh cool, I understand that now. I made it so the force ranges from 0 to 10000 as that's what Windows defines as the range for the amplitude of the force so I'd get the maximum useful resolution.
I have to add some documentation around all of this so that other people can continue this. I'll finish completing the missing features I think a complete clone of the MS FFB2 needs and then work on it

**Comment by fcppenta** [comment]
For now it's working very realistic, only one thing I noticed. Using Microsoft FFB Sidewinder 2 I noticed that the joystick behavior using aircrafts is not well, in fact when the aircraft engine is not working the joystick should be full forward, when running the center will depend of the thrust. So in Sidewinder it works like an inverse sense of the forces. So my my own yoke with your library, It's working like the real one (I'm a pilot private so I know what I'm talking about). The only thing is inversed is hen I try to trim. If I put the nose down with the trim the yoke should go forward, but instead it comes back :(
Do you think is there anything that could be done ?

**Comment by jmriego** [comment]
if I understand the issue correctly I think I saw something similar when using some other yoke code I found when creating this.

What I think you need to do in your yoke sketch is when sending the y axis position, invert it (it probably would just be multiply it by -1). Of course that would mean that you'd also have to invert the current axis configuration in your sim. Not completely sure though!

I'd recommend you testing to be sure with the ForceTest.exe and the constant force with different angles to make sure the axes are right:
0 should be towards you (pitch up if you prefer), 90 should be towards the left side

**Comment by fcppenta** [comment]
It's not work, because when using the trim wheel, we are changing the spring effect new center... So inverting the constant force does not work. That's a shame because I've all correct except the trim wheel, also I sent an email to the developed XPForce for X-Plane, just to see if it's possible to invert the trim effects, I think he can put a checkbox to invert it... We'll see.

**Comment by jmriego** [comment]
sorry what I meant is that it's typical this to happen if the forces are inverted. I'd debug it in this order:

1. check the constant force. 0 should be towards you (pitch up if you prefer), 90 should be towards the left side
2. If the y forces are inverted, fix that by multiplying by -1 all forces sent to the pitch motor. Maybe something like `analogWrite(whatever you have *-1)`
3. if you had to change the y forces, you also will have to invert the y axis position (or at least the y axis position sent to the spring effect by setting `effects[1].springPosition = yourcurrentsetting * -1`

go through these steps. they should fix that as the offset the sim will send you will still be the same after you make these changes

**Comment by fcppenta** [comment]
unfortunately no chances for the moment, IT's really weird that Microsoft FFB Sidewinder 2 has the  opposito effect that it should be, or, the x-plane plugin sends the forces with trim on the opposite direction...

**Comment by fcppenta** [comment]
One more thing, and probably is what is wrong with the library, I think. The spring effect, in fact, it's not working correctly, it simply turns X axis one direction, and Y axis also (towards me), so to correct it I had to join this code in Joystick.cpp for the spring effect

if (force > 0) {
				force = force - 5000;
			}
			else {
				force = force + 5000;
			}

			force = ((force * 512) / 10000); //range of force from -255 to 255

After it, it works, it puts the X and Y axis on the center.

**Comment by fcppenta** [comment]
Another thing :)
Microsoft Sidewinder FFB2 is good, I was wrong thinking it was not good, because I had also My own hardware connected. With only Microsoft Sidewinder connected it's good all the forces around. So definitely  there must exist an error in the library, I think. I'll try to debug it everywhere ;)

**Comment by jmriego** [comment]
I did some more testing in case I was missing something but everything is good on the library. I am convinced there is something you are missing in your sketch. You should never have the need to modify the `src/Joystick.cpp` unless there was really a bug, definitely not necessary just because you are using a different motor

Please have a look at the instructions I posted above and instead of trying to test in a game just use the `ForceTest.exe` spring effect and play with the offset parameters. In both the MS FFB2 and using this library a offset of 50 in the pitch axis will bring the spring center towards you

**Comment by jmriego** [comment]
oh and there's no need to change effect by effect to make them in the range of 255. All effects are currently returning a value between -10000..10000. If you want a value in the range -255..255 you can change the gain to 0.0255

Another option is to map the value with the [map function](https://www.arduino.cc/reference/en/language/functions/math/map/) `myforce = map(forces[0], -10000, 10000, -255, 255)`

**Comment by fcppenta** [comment]
OK, I got it, just found what was not good on on my hardware.

**Comment by fcppenta** [comment]
And thank you for your support.

**Comment by jmriego** [comment]
no worries. glad you got it working!
