### ISSUE TITLE
Joystick is vibrating

### ISSUE THREAD

**Issue by JayPi01** [jmriego/Fino#16]
Hi, I use two BTS7960B H-Bridges with the mechanic of an old MS Sidewinder II  that are connected to a Pro Micro. The position is read by the pot value of two analog in pins. Unfortunately the Joystick is a little vibrating when using with Joytest Spring function. Do you guys have an idea what to do?

Fino.ino

#define DEBUGNO
// the digits mean Mmmmrrr (M=Major,m=minor,r=revision)
#define SKETCH_VERSION 2004000

#include "src/Joystick.h"
#include "config.h"

// -------------------------
// Various global variables
// -------------------------
unsigned long lastEffectsUpdate;
unsigned long nextJoystickMillis;
unsigned long nextEffectsMillis;

// --------------------------
// Joystick related variables
// --------------------------

#define minX 110
#define maxX 982
#define minY 100
#define maxY 878

bool is_connected = false;
bool forces_requested = false;
bool pos_updated = false;

int16_t pos[2] = {0, 0};
int lastX;
int lastY;
int lastVelX;
int lastVelY;
int lastAccelX;
int lastAccelY;

EffectParams effects[2];
int32_t forces[2] = {0, 0};

Joystick_ Joystick(
    JOYSTICK_DEFAULT_REPORT_ID, JOYSTICK_TYPE_JOYSTICK,
    0, 0, // Button Count, Hat Switch Count
    true, true, false, // X, Y, Z
    false, false, false, // Rx, Ry, Rz
    false, false); // rudder, throttle

void setup() {
    pinMode(A0,INPUT);
    pinMode(A2,INPUT);
    pinMode(2,OUTPUT);
    pinMode(3,OUTPUT);
    pinMode(10,OUTPUT);
    pinMode(9,OUTPUT);
    pinMode(5,OUTPUT);
    pinMode(6,OUTPUT);

    setupJoystick();
    
    // setup communication
    Serial.begin(9600);
    // setup timing and run them as soon as possible
    lastEffectsUpdate = 0;
    nextJoystickMillis = 0;
    nextEffectsMillis = 0;
}

void loop(){
  
    pos[0] = analogRead(A0);
    pos[1] = analogRead(A2);

    unsigned long currentMillis;
    currentMillis = millis();
    // do not run more frequently than these many milliseconds
    if (currentMillis >= nextJoystickMillis) {
        updateJoystickPos();
        nextJoystickMillis = currentMillis + 2;

        // we calculate condition forces every 100ms or more frequently if we get position updates
        if (currentMillis >= nextEffectsMillis || pos_updated) {
            updateEffects(true);
            nextEffectsMillis = currentMillis + 100;
            pos_updated = false;
        } else {
            // calculate forces without recalculating condition forces
            // this helps having smoother spring/damper/friction
            // if our update rate matches our input device
            updateEffects(false);
        }
  
    }
    
    if(forces[0] > 0){
      digitalWrite(2,HIGH);
      analogWrite(9,abs(forces[0]));
      analogWrite(10, 0);
    } else {
      digitalWrite(2,HIGH);
      analogWrite(9,0);
      analogWrite(10,abs(forces[0]));
   }

   if(forces[1] > 0){
     digitalWrite(3,HIGH);
     analogWrite(5,abs(forces[1]));
     analogWrite(6,0);
    } else {
     digitalWrite(3,HIGH);
     analogWrite(5,0);
     analogWrite(6,abs(forces[1]));
   }   
   
   delay(1);

}

joystick.ino:

void setupJoystick() {
    Joystick.setXAxisRange(minX, maxX);
    Joystick.setYAxisRange(minY, maxY);
    Joystick.begin();
}

void updateJoystickPos() {
    Joystick.setXAxis(pos[0]);
    Joystick.setYAxis(pos[1]);
}

void updateEffects(bool recalculate){

    for (int i =0; i < 2; i++) {
        effects[i].frictionMaxPositionChange = 25; // TODO: find proper values for these automatically
        effects[i].inertiaMaxAcceleration = 10;
        effects[i].damperMaxVelocity = 150;
    }
  
    effects[0].springMaxPosition = maxX;
    effects[1].springMaxPosition = maxY;
    effects[0].springPosition = pos[0] - 606;
    effects[1].springPosition = pos[1] - 552;

    unsigned long currentMillis;
    currentMillis = millis();
    int16_t diffTime = currentMillis - lastEffectsUpdate;

    if (diffTime > 0 && recalculate) {
        lastEffectsUpdate = currentMillis;
        int16_t positionChangeX = pos[0] - lastX;
        int16_t positionChangeY = pos[1] - lastY;
        int16_t velX = positionChangeX / diffTime;
        int16_t velY = positionChangeY / diffTime;
        int16_t accelX = ((velX - lastVelX) * 10) / diffTime;
        int16_t accelY = ((velY - lastVelY) * 10) / diffTime;
    
        effects[0].frictionPositionChange = velX;
        effects[1].frictionPositionChange = velY;
        effects[0].inertiaAcceleration = accelX;
        effects[1].inertiaAcceleration = accelY;
        effects[0].damperVelocity = velX;
        effects[1].damperVelocity = velY;

        #ifdef DEBUG
        Serial.print(currentMillis);
        Serial.print("X");
        Serial.print(pos[0]);
        Serial.print("Y");
        Serial.print(pos[1]);
        Serial.print("C");
        Serial.print(positionChangeX);
        Serial.print(",");
        Serial.print(positionChangeY);
        Serial.print("V");
        Serial.print(velX);
        Serial.print(",");
        Serial.print(velY);
        Serial.print("A");
        Serial.print(accelX);
        Serial.print(",");
        Serial.print(accelY);
        #endif

        lastX = pos[0];
        lastY = pos[1];
        lastVelX = velX;
        lastVelY = velY;
        lastAccelX = accelX;
        lastAccelY = accelY;
    } else {
        effects[0].frictionPositionChange = lastVelX;
        effects[1].frictionPositionChange = lastVelY;
        effects[0].inertiaAcceleration = lastAccelX;
        effects[1].inertiaAcceleration = lastAccelY;
        effects[0].damperVelocity = lastVelX;
        effects[1].damperVelocity = lastVelY;
    }

    Joystick.setEffectParams(effects);
    Joystick.getForce(forces);

    //Serial.print("pos: ");Serial.print(pos[0]);Serial.print("  ");Serial.println(pos[1]);
    //Serial.print("force: ");Serial.print(forces[0]);Serial.print("  ");Serial.println(forces[1]);    

    #ifdef DEBUG
    if (diffTime > 0 && recalculate) {
        Serial.print("F");
        Serial.print(forces[0]);
        Serial.print(",");
        Serial.println(forces[1]);
    }
    #endif
}

**Comment by SchmidtFranz** [comment]
Could you write a little sketch that just outputs the raw potentiometer data over serial? To see if it's fluctuating a little when no movement is present on the stick.

**Comment by JayPi01** [comment]
The values are slighly drifting around the last digit. The nearly same code works well with the YukMingLaw lib. Is there a bigger 'Deadzone' in the YukMingLaw lib? Cant find it in the code.

**Comment by jmriego** [comment]
I think that makes sense if you were using that code before. There's one change I made compared to that library that the forces go 0 to 10000 instead of 0 to 255. You can use something like: `map(force[0], 0, 10000, low_force, high_force)` as the value to send to `AnalogWrite`

`low_force` would be the minimum force that makes your motor start moving. It's probably not 0. If you use a 0 to 255 range low forces will probably have absolutely no effect on the joystick and things like a spring would have a massive deadzone. In my case I used around 60
`high_force` the maximum force you want to use. In my case I used around 192

Take into account that the firmware cannot guess what's the correct values for the specific motor you are using. This all depends on motors and probably things like the weight or friction

**Comment by JayPi01** [comment]
Thanks for your help! 
Think that was the right direction. Divided the incoming forces by 10000 and mapped these values to -255 .. 255 in Joystick.cpp, method Joystick_::forceCalculator. Now the vibrations are gone and the maximum forces I write to AnalogWrite are max. 65.

**Comment by JayPi01** [comment]
Dividing by 2500 and mapping to -255 .. 255 is good. Now there are maximum forces and no vibrations. :)

**Comment by jmriego** [comment]
glad to hear that! closing this ticket then. I definitely need to add more documentation around all of this
