### ISSUE TITLE
ForceTest.exe Groves effect working but minor bug

### ISSUE THREAD

**Issue by SchmidtFranz** [jmriego/Fino#2]
I tested the groves effect in forcetest.exe again and now it does work correctly but only after activating and deactivating and then activating again. After startup of forcetest.exe the first activation shows the same behavior as before the fix (vibrating insteat of grooves). After that it works as it should. With the MSFFB2 the effect works on the first activation.

Thanks aging for your work on this.

**Comment by jmriego** [comment]
mmmm that's strange, I can see the difference. This is going to be a really difficult thing to figure I'm afraid

**Comment by SchmidtFranz** [comment]
Maybe it's related to issue #1 I don't really know, also to make things more difficult, on my new test setup I noticed that after the groves effect works correctly, the intensity changes up and down like a sine wave, (intensity goes up and down maybe over the time of 5 seconds).

**Comment by jmriego** [comment]
not sure if you have done anything like this, but it's possible to rename the USB devices doing some config to the Arduino boards.txt file but as soon as I did that the groves effect stops working. I have no idea why but maybe Windows keeps in some place the info about the supported capabilities of the device

**Comment by SchmidtFranz** [comment]
Maybe copying the name and device id off a sidewinder 2 ffb, so it appears as one to windows helps, I'm not at my pc at the moment so I can't test it.

**Comment by jmriego** [comment]
that's a very good idea. I'll definitely do some testing around that.
By the way, I found some info about the msffb2 which helped me on this that might be useful: https://www.descentbb.net/viewtopic.php?f=8&t=19061

**Comment by jmriego** [comment]
Just leaving this for my own notes. List of USB messages received while starting ForceTest.exe and trying the grooves effect:

> Start program:
C 04 04 
D FF 04 
C 03 04 
3 01 00 00 00 00 00 00 00 10 27 10 27 00 00 8E 
3 01 01 00 00 00 00 00 00 10 27 10 27 00 00 8E 
1 01 08 FF FF 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0
3 02 00 00 00 00 00 00 00 10 27 10 27 00 00 00 
3 02 01 00 00 00 00 00 00 10 27 10 27 00 00 00 
1 02 0B FF FF 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0
3 03 00 00 00 00 00 00 00 10 27 10 27 00 00 00 
3 03 01 00 00 00 00 00 00 10 27 10 27 00 00 00 
1 03 09 FF FF 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0
5 04 00 00 FF 
1 04 01 FF FF 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0
4 05 00 00 00 00 00 00 00 00 00 00 00 
1 05 04 FF FF 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0
4 06 00 00 00 00 00 00 28 00 00 00 00 
1 06 04 14 00 00 00 01 00 FF FF 04 00 00 00 00 00 00 00 00 03 
sD: 0

> Activate grooves:
4 06 7C 15 00 00 00 00 28 00 00 00 00 
A 06 01 FF 00 

> Deactivate grooves:
A 06 03 00 00 
A 06 03 00 00 
B 06 03 

> Activate grooves:
4 06 7C 15 00 00 00 00 28 00 00 00 0A 
1 06 04 14 00 00 00 01 00 FF FF 04 00 00 BC 02 00 00 00 00 75 
sD: 700
A 06 01 FF 00 

> Deactivate grooves:
A 06 03 00 00 
A 06 03 00 00 
B 06 03

**Comment by jmriego** [comment]
hey @SchmidtFranz your hunch was right, this can be solved by using the MS FFB2 VID and PID!
That still doesn't explain what's the proper solution for it but at least it's a workaround for now.

Here's a link with the instructions to modify the USB device name, VID and PID: http://liveelectronics.musinou.net/MIDIdeviceName.php

You want to set these two lines:
```
micromusinou.build.vid=0x045e
micromusinou.build.pid=0x001b
```

**Comment by jmriego** [comment]
I have been doing some testing and I think I have a fix for it. Can you check the #7 branch and let me know if that works for you? Thanks!

**Comment by SchmidtFranz** [comment]
I'm going to try it sometime this week

**Comment by jmriego** [comment]
hi @SchmidtFranz , I merged the code into the main branch so it should be all good now. I have done quite some testing but if you find it doesn't work for you feel free to reopen this. Cheers

**Comment by SchmidtFranz** [comment]
@jmriego thanks I couldn't get my test set-up finished last week because my 3d printer had some mayor Problems. Next week I'm going to work on the FBB stick again. I'm going to report back if I find anything.

**Comment by jmriego** [comment]
no worries @SchmidtFranz ! I only found time to test it properly this weekend. If you find that it doesn't work for you it might very possibly be that Windows is not detecting the new features of the device because it thinks it's the same one. Just make sure to follow those instructions on the link I sent you about changing the VID and PID and set any VID/PID you want

**Comment by SchmidtFranz** [comment]
@jmriego I have a nother problem that could be related to device pid, I'm using xp force for msfs and it recognizes the The joystick as a FFB device, but then the ffb doesn't work. It worked briefly when I set the device name pid/vid to the same one my msffb2 has but then I had to calibrate the axis in windows and since then it doesn't work anymore. In FB test exe everything seams to work fine.

**Comment by jmriego** [comment]
I'm not sure what could be the issue for that. You could try uninstalling the previous devices that Windows found and see if that makes any change:
1. Go to Device Manager
2. Go to the menu bar and click on view->show hidden devices
3. Find the different devices you have been using and uninstall them
4. Maybe after that, restart windows

It's also strange that it suddenly stops working. Does this happen only with xp force? is this the first time you check xp force? Asking just in case this is something that is only affecting that program. Maybe test with fedit.exe

Another thing you could do is compile the sketch with `#define DEBUG` instead of `DEBUGNO`. That will send messages to the com port that you can see with the Arduino Ide. The forces should appear after a F (eg. F100,0 means force to the right)

**Comment by SchmidtFranz** [comment]
I got it solved, for whatever reason xp force doesn't like the joystick input range from -32768 to 32767 so I mapped it down to -300 to 300 for testing and it seems to work now.

**Comment by SchmidtFranz** [comment]
> hey @SchmidtFranz your hunch was right, this can be solved by using the MS FFB2 VID and PID!
> That still doesn't explain what's the proper solution for it but at least it's a workaround for now.
> 
> Here's a link with the instructions to modify the USB device name, VID and PID: http://liveelectronics.musinou.net/MIDIdeviceName.php
> 
> You want to set these two lines:
> 
> ```
> micromusinou.build.vid=0x045e
> micromusinou.build.pid=0x001b
> ```

Maybe this should be in the description of the project.

If you want I can write a little guide/description on how to set up the whole project, with a example for 2 pwm outputs and potentiometer inputs to make it easier for starters.
Because atm there are a few people searching for something like this in the eagle Forum.

**Comment by jmriego** [comment]
That would be great!
I've been meaning to write some documentation but I still haven't done much with potentiometers, etc.
If you can write the part about the hardware I'm more than happy to document the rest.
I'm not at home for work reasons for a few months so can't do much work on Fino, but perfect timing for documenting
