### ISSUE TITLE
Use this code to drive motors and pots directly?

### ISSUE THREAD

**Issue by crimzzon92** [jmriego/Fino#20]
Hi! I am currently trying to work out how to change the code so it will work whit motors and pots directly. I have a working FFB Yoke but no code and my knowledge are limited regarding coding. I do learn but it takes time. Is there any chance that someone has this project written for controlling motors and pots directly??

Thanx!!

**Comment by SchmidtFranz** [comment]
I have some code somewhere where basically the input is a number from encoder and output to serial with motor strength but it's from an older version of this library so I think it needs some modification, i can send it to you tomorrow

**Comment by crimzzon92** [comment]
> I have some code somewhere where basically the input is a number from encoder and output to serial with motor strength but it's from an older version of this library so I think it needs some modification, i can send it to you tomorrow

That would be great! thank you!

**Comment by jmriego** [comment]
hi @crimzzon92 !

I definitely need to add some documentation to this library to make it easier to use.
@SchmidtFranz will be able to give you some more info about the code for driving the motors as honestly I haven't done that myself yet.

The easiest start would be to get the code in this repo as is and supposing you use Analog 2 and 3 for input X and Y axes you can modify the `setup()` function in `Fino.ino` by adding these:

```
void setup() {
...
    pinMode(A0,INPUT);
    pinMode(A2,INPUT);
}
```

then after the setup add these two functions:
```
void ReadPots()
{
    pos[0] = map(analogRead(A2), 0, 1023, minX, maxX);
    pos[1] = map(analogRead(A3), 0, 1023, minY, maxY);
    pos_updated = true;
}

void DriveMotors()
{
   ... not sure what to put here yet ...
}
```

then as the first and last commands in loop use these functions:
```
void loop() {
    ReadPots()
    ...
    DriveMotors()
}
```

Hope this helps! that's a start but the main issue is going to be in fine tuning the motors strength, inertia and feeling because that totally depends on the parts you are using. Happy to help if I can though

**Comment by crimzzon92** [comment]
Hi! Thank you! It got me to understand a bit more what to do. 
-------------------------------------------------------------------------------------
is this code to replace all void loop code in the fino.ino file, you mean?

void loop() {
    ReadPots()
    ...
    DriveMotors()
}
-------------------------------------------------------------------------------------
I am still not sure how to give the motors instructions. Maybe something like this?

void loop() {
        // X Axis Funktion
  if(forces[0] > 0){
    digitalWrite(ROLL_L_EN,HIGH);
    digitalWrite(ROLL_R_EN,HIGH);
    analogWrite(ROLL_R_PWM,abs(forces[0]));
  }else{
    digitalWrite(ROLL_L_EN,HIGH);
    digitalWrite(ROLL_R_EN,HIGH);
    analogWrite(ROLL_L_PWM,abs(forces[0]));
  }
-------------------------------------------------------------------------------------

Thnax for all help!!

**Comment by jmriego** [comment]
I'll try to help you but I'm not in front of my computer now.

That's what you should have as the DriveMotors function
```
void DriveMotors() {
// X Axis Funktion
if(forces[0] > 0){
digitalWrite(ROLL_L_EN,HIGH);
digitalWrite(ROLL_R_EN,HIGH);
analogWrite(ROLL_R_PWM,map(abs(forces[0]), 0, 10000, 1, 244));
}else{
digitalWrite(ROLL_L_EN,HIGH);
digitalWrite(ROLL_R_EN,HIGH);
analogWrite(ROLL_L_PWM,map(abs(forces[0]), 0, 10000, 1, 244));
}
```

Where I wrote 1 and 244 those are the minimum and maximum forces you need your motor to send. Many motors might not start moving until the number is 40 or 50.

About this....
```
void loop() {
ReadPots()
...
DriveMotors()
}
```

I mean add read pots at the beginning and drive motors at the end but leave the rest unchanged

**Comment by crimzzon92** [comment]
I have tried the code and I get it to show up and I can calibrate the axis and so. But when trying to use the force tester there is no response from the motors, any idee?

**Comment by jmriego** [comment]
sounds like great progress! I don't think I really can't tell you much without learning about the motors you are using, the bridge, pins and all of that. For any project as big as doing your own joystick is better if you start small.
Forget completely about Force Feedback first. Try to start creating a sketch that when you press a button sends constant force to one side for example. Then try the other side. Or just a constant force all the time would help.

Once you get that working you are in a much better position to integrate it into the whole joystick code and you know a lot better what you need to put in `MotorFunctions`

**Comment by jmriego** [comment]
hi @crimzzon92 , I have just added some code to the repo with basically what I showed you before. After this change, I think all your code would only need to be in the `Arduino.ino` file. Hope this helps a bit!

**Comment by jmriego** [comment]
closing but let me know if there's anything else I can help you with
