### ISSUE TITLE
STM32F103

### ISSUE THREAD

**Issue by vtrx-az** [jmriego/Fino#21]
Hello.
I'm developing a port for the BluePill board.
I didn't use the Arduino platform because I don't have much knowledge in C++.
Could you try to help me find two problems related to the code?
1-Re-initialize joystick(ForceTeste.exe)stuck.
2-Using the iRacing Force Feedback Test 1.72 program, the effect stops after a while in testing.
The code is practically the same used in Arduino, but uses the C language and the Keil compiler.
It would be a cheap and efficient alternative.

**Comment by jmriego** [comment]
hi @vtrx-az !

That's going to be a bit tricky. Definitely the most difficult part for me is when getting the USB commands to work properly.
I've never heard of this board before but it seems like there are some ways of making it work with the Arduino IDE. Not sure if that would make this easier but just in case you didn't look at that.

What I usually do for this type of stuff is testing that the USB messages arrive and making the board blink after every message, send the received message through the Serial port or similar. That way you can see what message is exactly making the board hang which is probably what is happening to you.

There's one app that allows you to send USB messages called SimpleHIDWrite. Maybe I can send you some sample messages to test. I have saved the USB messges sent for setting up the joystick, for starting a effect, etc.

**Comment by vtrx-az** [comment]
Thanks for answering.
I have this application and I have the sources, it is compiled in Delphi, and I program in Delphi.
I would like the messages.
My email is z80s@hotmail.com.

**Comment by jmriego** [comment]
Just in case it helps someone else. These are the messages I use for a basic test of USB functionality:

1. ffbsetup: enable the force feedback device
2. ffbstartconst: start a constant force effect
3. ffbstopconst: stop the constant force effect
4. ffbclose: disable the force feedback device


[ffbsetup.txt](https://github.com/jmriego/Fino/files/8248334/ffbsetup.txt)
[ffbstartconst.txt](https://github.com/jmriego/Fino/files/8248335/ffbstartconst.txt)
[ffbstopconst.txt](https://github.com/jmriego/Fino/files/8248336/ffbstopconst.txt)
[ffbclose.txt](https://github.com/jmriego/Fino/files/8248337/ffbclose.txt)

Does this mean you actually got the BluePill board working with FFB?

**Comment by vtrx-az** [comment]
Yes, the BluePill board (STM32F103) is working as if it were an Arduino Leonardo implementation.
I'm trying to optimize the code and find out why it crashes when I use the FCM.exe application.
If it crashes then something is still missing.

**Comment by jmriego** [comment]
sorry, what's FCM.exe? I can't really fix something for the BluePill as I don't have one and I don't see much need in supporting this when Arduino works fine. I understand your use case and I can help you figure it out, but without more info it really can be anything

can you try different programs and if possible something that would send you some kind of log?

**Comment by vtrx-az** [comment]
https://forum.projectcarsgame.com/showthread.php?35147-Baseline-Wheel-FFB-Values-Google-Sheet-amp-FCM-Universal

**Comment by jmriego** [comment]
sorry but I think there's something else you might need to change for the BluePill board. I can confirm that program tests correctly on an Arduino Micro
![image](https://user-images.githubusercontent.com/15045950/159789200-f2167c4b-e7bc-4305-9aa2-93782e992155.png)

![image](https://user-images.githubusercontent.com/15045950/159789289-1a47eeaa-7fc9-4b83-9aa7-e66cd1e905ab.png)

I can't tell you what the issue is but my guess would be it's related to the USB communication

**Comment by vtrx-az** [comment]
I will try to find the problem.
I'm using a potentiometer for testing, if the position is all to one side (positive value), the program works without crashing, but if I start to rotate decreasing the X value, it stops.

**Comment by jmriego** [comment]
that's really strange. I don't know if it's related to this at all as even if you put a wrong number it shouldn't completely crash everything, but just make sure that the min and max values for the X axes are simetric (e.g. -10000 and 10000). The conditional effects won't work correctly if you try to make the X axis have only values between 0 and 10000 for example
