### ISSUE TITLE
rFactor 2

### ISSUE THREAD

**Issue by vtrx-az** [jmriego/Fino#22]
I tested with rFactor 2, the effects are not activated?

**Comment by jmriego** [comment]
can you give me a bit more info about that? what device are you using? does rFactor 2 detect the FFB joystick and the position?

**Comment by vtrx-az** [comment]
I did an initial test with Arduino leonardo.
In the control options you have to choose 'keyboard', with this choice the force feedback works as if the 'spring' effect was only enabled, that's all.
I looked on the internet and it seems that this game uses the periodic effect type effect.
I've been reading the link but I don't understand if it works or not.

https://github.com/fernandoigor/BRWheel

**Comment by jmriego** [comment]
I don't know anything about rFactor 2 but probably you have to choose the joystick in the control options. Games usually only map force feedback effects to the same joystick/wheel you are using as input

**Comment by jmriego** [comment]
also I went through that link and that looks like an alternative firmware for the Arduino Leonardo to show up as a wheel. It should be a bit more plug and play but you can't make it any way you want as you can with this repo that gives you freedom to choose as many axes, buttons and effects you want to use

**Comment by jmriego** [comment]
closing but let me know if there's anything else I can help you with
