### ISSUE TITLE
Sometimes hard shakes

### ISSUE THREAD

**Issue by gagagu** [jmriego/Fino#26]
Hi,
first, thanks for your work!
I've created a 3d printed Force Feedback Yoke based on your code (see https://github.com/gagagu/Arduino_FFB_Yoke) as a free GitHub project. 

The yoke seems to work but sometime (nearly often) i have hard movement or shakes that could damage my yoke so i have to reduced the pwm power signal of the dc motos.
I sadly do not understand how the effect settings works and hopefully would like to ask you if you can give me a hint what i could do or which setting i have to change to make everything smoother and not shaking hard in this way?

see a video if you like: https://youtu.be/QJRdzPXO4O4

Thanky foward

**Comment by jmriego** [comment]
hi @gagagu ! glad you are finding this useful.

There are two main possible reasons why the joystick can start shake:
1. flaky sensors
2. too strong forces

I'd say the best thing to do would be to try to get the readings of the x and y positions in real time with no forces involved and check if there's any shaking of the position. try to use some program that shows in the position in real time. in a pinch, "USB Game Controllers" Windows dialog would do it. if the position looks stable the next thing to check is lowering the forces and seeing if the controller still shakes.

By the way, this looks dope!
