### ISSUE TITLE
Error in Joystick.cpp

### ISSUE THREAD

**Issue by gagagu** [jmriego/Fino#27]
Hi,
i guess i've found an possibly error in your code in Joystick.cpp

the part 
for (int i=0; i <= FFB_AXIS_COUNT; ++i)
should be
for (int i=0; i < FFB_AXIS_COUNT; ++i)

on FFB_AXIS_COUNT = 2 the loop will run tree times instead of two.

void Joystick_::begin(bool initAutoSendState)
{
	_autoSendState = initAutoSendState;
	sendState();
    for (int i=0; i <= FFB_AXIS_COUNT; ++i)  //here it should be -> for (int i=0; i < FFB_AXIS_COUNT; ++i)
    {
        damperFilter[i] = LowPassFilter(cutoff_freq_damper, sampling_time_damper);
        inertiaFilter[i] = LowPassFilter(cutoff_freq_damper, sampling_time_damper);
        frictionFilter[i] = LowPassFilter(cutoff_freq_damper, sampling_time_damper);
    }
}

greetings

**Comment by jmriego** [comment]
just uploaded the fix. all seems to be working the same. I definitely need to create some unit tests!
thanks for your report
