### ISSUE TITLE
Using FFB on the Z axis

### ISSUE THREAD

**Issue by GO63-samara** [jmriego/Fino#30]
First, thank you for your wonderful work `Arduino Joystick with Force Feedback`.
And I have a question.

I see that it is possible to use FFB on the Z axis. How can this be used?
As far as I know, games do not support FFB on the Z axis. Or did I forget about some game?
In what test program can you test the FFB on the Z axis?
By Z axis do you mean pedals?

Thank you!

**Comment by jmriego** [comment]
no worries! good to see more people using it always

Honestly I don't know of any examples of games or sims using the Z axes for forces, but if you look in the `reference` folder you should see the file `pid1_01.pdf` 
In there I see some documentation about forces on the Z axes, but honestly I don't have any examples of them.
I haven't tried it, but maybe the `fedit.exe` utility allows you to choose force on a third axis
