### ISSUE TITLE
Missing implementation of some functions.

### ISSUE THREAD

**Issue by GO63-samara** [jmriego/Fino#31]
The `Joystick.cpp` file lacks the implementation of functions: `setRxAxis()`,  `setRyAxis()`,  `setRzAxis()`

Add this to the `Joystick.cpp` file:
```
void Joystick_::setRxAxis(int16_t value)
{
	_xAxisRotation = value;
	if (_autoSendState) sendState();
}

void Joystick_::setRyAxis(int16_t value)
{
	_yAxisRotation = value;
	if (_autoSendState) sendState();
}

void Joystick_::setRzAxis(int16_t value)
{
	_zAxisRotation = value;
	if (_autoSendState) sendState();
}
```
Thanks!

**Comment by jmriego** [comment]
good catch! this is something I removed when I started this repo to save some code space but totally missed to put it back. Fixed with #33
