### ISSUE TITLE
Support for up to four operating Hat switches

### ISSUE THREAD

**Issue by GO63-samara** [jmriego/Fino#37]
@jmriego
What do you think about the possibility of adding support for up to 4 working Hat Switches to the project?
Already have a PR: https://github.com/jmriego/Fino/pull/36

**Comment by jmriego** [comment]
yes, I think that makes sense. I'd like to review this a bit more. This PR includes a bit more stuff than what I would have expected to be necessary for adding 4 hat switches.

For example, I'd like to check what's the impact of using `db` function for adding bytes to the descriptor. I understand the code is a bit easier to read, but does it make it bigger or smaller? It's forcing the Joystick to require a private variable with the size.

Also, why is that change with the buttons required? It seems like you have moved the button values variables a lot earlier in the code but I'm not sure why is that change needed.

I'd love to figure out a why to have some kind of testing simulating Arduino as a USB device so I don't have to test PR manually before merging. This is making PR slower than it should

**Comment by GO63-samara** [comment]
> For example, I'd like to check what's the impact of using db function for adding bytes to the descriptor. I understand the code is a bit easier to read, but does it make it bigger or smaller? It's forcing the Joystick to require a private variable with the size.


Well, right now I checked the sizes of all code options:

```
Joystick with 8 Axes 128 Buttons 2 Hats:
                                                PROGMEM     RAM
Fino-master                                   :   22040    1883  (b96a2b8)
More readable creation of HidReportDescriptor :   22066    1739  (b31580f)
Up to four HatSwitches are now supported      :   22048    1743  (408f9c9)
```


```
Joystick with 8 Axes 128 Buttons 0 Hats:          22046    1743  (408f9c9)
Joystick with 8 Axes 128 Buttons 1 Hats:          22046    1743  (408f9c9)
Joystick with 8 Axes 128 Buttons 2 Hats:          22048    1743  (408f9c9)
Joystick with 8 Axes 128 Buttons 3 Hats:          22048    1743  (408f9c9)
Joystick with 8 Axes 128 Buttons 4 Hats:          22048    1743  (408f9c9)

```

Occupied PROGMEM increased by only 8 bytes. The occupied RAM is reduced by 140 bytes.




> Also, why is that change with the buttons required? It seems like you have moved the button values variables a lot earlier in the code but I'm not sure why is that change needed.

I moved the calculation of `_hidReportSize` and `_buttonValuesArraySize` higher when I introduced the `db()` functions. Now it is clear that it was superfluous and does not affect the result. You can again move the calculation of `_hidReportSize` and `_buttonValuesArraySize` down.
 



> I'd love to figure out a why to have some kind of testing simulating Arduino as a USB device so I don't have to test PR manually before merging. This is making PR slower than it should


I've been testing with the soft method, simply because I don't have the physical four Hats. In all cases I used the code:

```
static unsigned HATtime;
const int hat[] = {0, 45, 90, 135, 180, 225, 270, 315};
const byte hatsize  = (sizeof(hat) / sizeof(*hat));
const unsigned hat_delta = 40;

++HATtime %= hat_delta * hatsize;
int angle  = HATtime / hat_delta % hatsize;

Joystick.setHatSwitch(0, hat[(angle+0) % hatsize]);
Joystick.setHatSwitch(1, hat[(angle+1) % hatsize]);
Joystick.setHatSwitch(2, hat[(angle+2) % hatsize]);
Joystick.setHatSwitch(3, hat[(angle+3) % hatsize]);

Joystick.sendState();
```
I pasted this code into the `void updateJoystickPos()` function. In the `void setupJoystick()` function, I include `Joystick.begin(false);` i.e. `_autoSendState == false`.

**Comment by Hyratel** [comment]
I have this done in my ports of the joystick library! properly handles the bit padding and everything

**Comment by GO63-samara** [comment]
I don't understand. What are you talking about?

**Comment by GO63-samara** [comment]
![image](https://user-images.githubusercontent.com/63638386/225134527-2f524577-fae0-4e29-989c-93294efb1d07.png)

**Comment by jmriego** [comment]
that app looks great. I actually spent quite some time searching for something like that and ended up creating my own tests in Python. Did you create it yourself?

For now I have merged you PR into the `four_hats` branch. I was looking into how to add code into this PR for what we talked above but it seems like I had to push code into your `master` branch which I didn't really want to do just in case.

The code I think looks good and I think I understand the changes now. I just want to be extra safe with the testing and simplifying things where changes are not needed but that's about it

**Comment by jmriego** [comment]
cool, I'll have a look there. I think I'll be using it for testing.

Sorry, what I meant is that by giving me permissions to contribute to the PR you gave me permissions to add code to your master branch and I didn't want to mess it up as you might be using it for your own stuff. I have lost the ability to edit it now that the PR has been closed though

**Comment by jmriego** [comment]
that's all good now. I'm testing this a bit already and playing with it. Thanks for your work here!

**Comment by jmriego** [comment]
I'm closing this one now as I just merged it to the repo. Sorry for the delay!
