### ISSUE TITLE
ffb motor noise

### ISSUE THREAD

**Issue by huseyinctlbs** [jmriego/Fino#5]
Hello. I have done some test on this yukminglaw repo before but i was getting too much noise on ffb motor. I have tried some pwm codes but didnt succeed. Would you add a template about it on your repo?

**Comment by SchmidtFranz** [comment]
I had that Problem too, because the pwm frequency on standard arduino is to low (and I too couldn't get it switched to a higher one), I switched to bldc motors and simplefoc and communicate the motor speeds via uart to the openfoc drivers. Easyest solution would be to get a external motor driver that communicates with spi, i2c or something similar.

**Comment by jmriego** [comment]
sorry @huseyinctlbs ! I don't have a motor to test this on. I'm using this as an interface with an existing joystick base and not creating my own motor interface.
I did a quick Google search and found info about changing PWM frequency and such but I'm afraid I won't be able to do anything about this

**Comment by jmriego** [comment]
hi @huseyinctlbs @SchmidtFranz !

I recently got a motor controller and started trying to control the MS FFB2 motors and got the same noise problem. Reading online, it seems like the Arduino PWM works on a frequency that humans can hear, but it's possible to change that frequency:
http://r6500.blogspot.com/2014/12/fast-pwm-on-arduino-leonardo.html

They mention that you can set pins 6 and 13 to frequencies up to 187khz but careful as that's probably not supported by your motor controller. In this example I'm setting it at 23Khz using his code:

```
/**********************************************************
   Fast PWM on pins 6, 13 (High Speed TIMER 4)
   
   Do not use analogWrite to pins 6 or 13 if using 
   this functions as they use the same timer.
   
   Those functions will conflict with the 
   MSTIMER2 library.
   Uses 7 PWM frequencies between 2930Hz and 187.5kHz
   
   Timer 4 uses a PLL as input so that its clock frequency
   can be up to 96MHz on standard Arduino Leonardo.
   We limit imput frequency to 48MHz to generate 187.5kHz PWM
   If needed, we can double that up to 375kHz
**********************************************************/

// Frequency modes for TIMER4
#define PWM187k 1   // 187500 Hz
#define PWM94k  2   //  93750 Hz
#define PWM47k  3   //  46875 Hz
#define PWM23k  4   //  23437 Hz
#define PWM12k  5   //  11719 Hz
#define PWM6k   6   //   5859 Hz
#define PWM3k   7   //   2930 Hz

// Direct PWM change variables
#define PWM6        OCR4D
#define PWM13       OCR4A

// Terminal count
#define PWM6_13_MAX OCR4C

// Configure the PWM clock
// The argument is one of the 7 previously defined modes
void pwm613configure(int mode)
{
    // TCCR4A configuration
    TCCR4A=0;
    
    // TCCR4B configuration
    TCCR4B=mode;
    
    // TCCR4C configuration
    TCCR4C=0;
    
    // TCCR4D configuration
    TCCR4D=0;
    
    // TCCR4D configuration
    TCCR4D=0;
    
    // PLL Configuration
    // Use 96MHz / 2 = 48MHz
    PLLFRQ=(PLLFRQ&0xCF)|0x30;
    // PLLFRQ=(PLLFRQ&0xCF)|0x10; // Will double all frequencies
    
    // Terminal count for Timer 4 PWM
    OCR4C=255;
}

// Set PWM to D6 (Timer4 D)
// Argument is PWM between 0 and 255
void pwmSet6(int value)
{
    OCR4D=value;   // Set PWM value
    DDRD|=1<<7;    // Set Output Mode D7
    TCCR4C|=0x09;  // Activate channel D
}

// Set PWM to D13 (Timer4 A)
// Argument is PWM between 0 and 255
void pwmSet13(int value)
{
    OCR4A=value;   // Set PWM value
    DDRC|=1<<7;    // Set Output Mode C7
    TCCR4A=0x82;  // Activate channel A
}

#define L_EN 8
#define R_EN 0
#define L_PWM 9
#define R_PWM 10


void TurnLeft(uint8_t pwm){
   pwmSet6(0);
   delayMicroseconds(100);
   pwmSet13(pwm);
}

void TurnRight(uint8_t pwm){
   pwmSet6(0);
   delayMicroseconds(100);
   pwmSet13(pwm);
}

void MotorEnable(){
  digitalWrite(L_EN,1);
}

void MotorDisable(){
  digitalWrite(L_EN,0);
}

void MotorStop(){
  analogWrite(L_PWM, LOW);
  analogWrite(R_PWM, LOW);
}




void setup() 
{
    pinMode(R_PWM, OUTPUT);
    pinMode(L_PWM, OUTPUT);
    pinMode(L_EN, OUTPUT);
    pinMode(R_EN, OUTPUT);
    pwm613configure(PWM23k);
}

void loop() 
{

  if(Serial.available() > 0)
  {
    int speed = Serial.parseInt();

    if (speed > 0)
    {
      MotorEnable();
      TurnRight(speed);
      delay(1000);
      MotorStop();
    }
    else if (speed < 0)
    {
      MotorEnable();
      TurnLeft(abs(speed));
      delay(1000);
      MotorStop();
    }
    else
    {
        MotorDisable();
    }
  }
  
}
```

This is a sketch that will wait for Serial input (Tools->Serial Monitor). Write any value between -255 to 255 to move the motor by that value. Test with values close to 0 first to know what is the minimum/maximum values that work for you

**Comment by huseyinctlbs** [comment]
Thanks for your search for us. But i have found this solution after writing here :)), I have forgot that i have asked for this problem and dont remember where i have found this code. The code i have using is that;

void pwmAdjust()
{
TCCR1A = (1 << COM1A1) | (0 << COM1A0) | (1 << COM1B1) | (0 << COM1B0) | (0 << COM1C1) | (0 << COM1C0) | (0 << WGM11) | (1 << WGM10);
TCCR1B = (0 << ICNC1) | (0 << ICES1) | (0 << WGM13) | (0 << WGM12) | (0 << CS12) | (0 << CS11) | (1 << CS10);
OCR1A = 0;
OCR1B = 0;
}

Im adding this prodecure in my motor used codes and call it in setup void. This code sets pwm frequency at 9 and 10 pins of leonardo and thats solves my noise problem. Thank you again.

**Comment by SchmidtFranz** [comment]
Thanks for the work on this @jmriego , I saw that too, but resorted to using two software serial ports to communicate with my bldc drivers.

Also a bit off topic, did you see this? He has a ffb implementation on stm32 but only implemented the basic stuff like spring, constant, periodic,... Supposedly he is going to open source it at some point.
https://forums.eagle.ru/topic/246873-honey-i-developed-ffb-joystick-diy/

**Comment by jmriego** [comment]
no worries @huseyinctlbs ! I was just figuring it out anyway and remembered about this ticket later. I'll check that code if that makes any difference with my motors as I'm just starting with all this.

I didn't notice that @SchmidtFranz thanks! I'll have a read at that and probably point him to this repo as almost everything here is working now. I think it's just the inertia effect that I need to improve the settings for but I'm happy with how this works for now. When I close the tickets I'll spend some time documenting all of this as it might help someone

**Comment by SchmidtFranz** [comment]
@jmriego I can give you my working code for my joystick or you take your own you are working on and put it as an example on here to make it easier for beginners to start with their own build.

And maybe you could look at arduino due support again, as I couldn't get it to work, if you don't have a due i would be happy to buy you one if you could look into it.

**Comment by huseyinctlbs** [comment]
@jmriego @SchmidtFranz friends i have another problem :)) the spring effect has too much deadzone. Is this possible could be because of  the motor driver? I have start pwm write at 10 with dismiss the first 9 value. This has solved quite but not enough. Did you have same problem?

**Comment by SchmidtFranz** [comment]
@huseyinctlbs yes I had the same Problem and solved it the same way basically mapping it from 300 to 3000 instead of 0 to 3000, i think it's because with this low amount of force it can't quite overcome the mechanical friction that is in the whole system (motor, gearing,...)

**Comment by jmriego** [comment]
same here, what I did is figure out with the sketch above what's the minimum force that starts moving the motors I'm using and the maximum force I want to use. Then, instead of sending to the motor a value from 0 to 255 I send this: `map(force value, 0, 255, minimum_useful_value, maximum_useful_value)`

**Comment by SchmidtFranz** [comment]
@jmriego I'm just waiting on my odrive board from China atm, I'm really excited to try it with the hoverboard Motors, because then the stick is direct drive wich should give a really good feel. I'm aiming for double the force the brunner stick has.

**Comment by jmriego** [comment]
that sounds great and hope it turns out as good as it sounds! :)

**Comment by JayPi01** [comment]
@SchmidtFranz  I'm just waiting on my odrive board from China atm, I'm really excited to try it with the hoverboard Motors, because then the stick is direct drive wich should give a really good feel. I'm aiming for double the force the brunner stick has.

Did you have any success with the odrive board?

**Comment by SchmidtFranz** [comment]
@JayPi01 i had some problems with my Chinese odrive clone and it blew up.
That brought me onto simplefoc project, and now I'm on a side quest 😂 to develop my own servo drive that I'm going to use for my force feedback stick. It's probably going to take another 2-3 months until I have the motor driver finished and then I'm back to my force feedback stick (maybe until then msfs2020 has proper helicopters also).
